In [34]:
from sklearn.svm import SVC, SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn

In [9]:
iris = datasets.load_iris(as_frame = True).frame

In [10]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [11]:
iris.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [12]:
X = iris.drop('target', axis = 1)
y = iris['target']

In [13]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42, stratify = y
)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train, y_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [20]:
y_pred = svc.predict(X_test_scaled)

In [26]:
from sklearn.metrics import accuracy_score, classification_report, f1_score

print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification : ", classification_report(y_test, y_pred))

Accuracy :  0.9333333333333333
Classification :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [27]:
svc = SVC(kernel = 'linear')
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification : ", classification_report(y_test, y_pred))

Accuracy :  0.9111111111111111
Classification :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.82      0.93      0.88        15
           2       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

In [30]:
svc = SVC(kernel = 'rbf')
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification : ", classification_report(y_test, y_pred))

Accuracy :  0.9333333333333333
Classification :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [31]:
C_vals = [0.5,1,2,3,4,5]

for c in C_vals:
    svc = SVC(kernel = 'rbf', C = c)
    svc.fit(X_train_scaled, y_train)
    y_pred = svc.predict(X_test_scaled)
    print("C : ", c, "Accuracy : ", accuracy_score(y_test, y_pred))
    # print("Classification : ", classification_report(y_test, y_pred))

C :  0.5 Accuracy :  0.9111111111111111
C :  1 Accuracy :  0.9333333333333333
C :  2 Accuracy :  0.9111111111111111
C :  3 Accuracy :  0.9111111111111111
C :  4 Accuracy :  0.9333333333333333
C :  5 Accuracy :  0.9333333333333333

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [39]:
data = datasets.load_diabetes(as_frame = True).frame

In [40]:
data.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [41]:
X = data.drop('target', axis = 1)
y = data['target']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42
)

In [53]:
y_scaler = StandardScaler()

y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1, 1)).ravel()
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1, 1)).ravel()

In [54]:
model = SVR()

model.fit(X_train, y_train_scaled)

SVR()

In [55]:
y_pred_scaled = model.predict(X_test)

In [56]:
from sklearn.metrics import r2_score
print("r2 score : ", r2_score(y_test_scaled, y_pred_scaled))

r2 score :  0.48844443151651884

In [57]:
model = SVR(kernel = 'linear')

model.fit(X_train, y_train_scaled)
y_pred_scaled = model.predict(X_test)
print("r2 score : ", r2_score(y_test_scaled, y_pred_scaled))

r2 score :  0.4433761323833776

In [59]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "C"  :[ 1, 2, 5, 10, 50],
    "kernel" : ['rbf', 'linear'],
    'epsilon' : [0.01, 0.1, 0.2, 0.3, 0.5]
    }

grid = GridSearchCV(
    SVR(),
    param_grid,
    cv = 5,
    scoring = 'r2'
)

grid.fit(X_train, y_train_scaled)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 5, 10, 50],
                         'epsilon': [0.01, 0.1, 0.2, 0.3, 0.5],
                         'kernel': ['rbf', 'linear']},
             scoring='r2')

In [60]:
y_pred = grid.predict(X_test)

In [63]:
print("r2 score : ", r2_score(y_test_scaled, y_pred))

r2 score :  0.47444183250401095

In [62]:
print(grid.best_params_)

{'C': 10, 'epsilon': 0.1, 'kernel': 'linear'}

In [66]:
from sklearn.svm import LinearSVR

model = LinearSVR(C = 10, epsilon = 0.1, max_iter = 10000)
model.fit(X_train, y_train_scaled)
y_pred_scaled = model.predict(X_test)
print("r2 score : ", r2_score(y_test_scaled, y_pred_scaled))

r2 score :  0.47483661088354123